apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: express-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/shikha-shrivastava6/Express-App-ArgoCD.git'
    path: k8s
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated: {}

