apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    {{ .Values.name }}
spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }} 
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}
        ports:
        - containerPort: {{ .Values.port }}
        resources:
          requests:
            memory: {{ .Values.resource.requests.memory }}
            cpu: {{ .Values.resource.requests.cpu }}
          limits:
            memory: {{ .Values.resource.limits.memory }}
            cpu: {{ .Values.resource.limits.cpu }}  
