apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - port: 80
      targetPort: {{ .Values.port }}

